export type Goal = "strength" | "hypertrophy" | "fat_loss" | "general";

export type BodyPart =
  | "chest"
  | "back"
  | "legs"
  | "shoulders"
  | "arms"
  | "push"
  | "pull"
  | "full_body";

export type GeneratorFocus =
  | BodyPart
  | "upper"
  | "lower"
  | "chest_shoulders"
  | "chest_triceps"
  | "back_biceps"
  | "back_rear_delts"
  | "shoulders_arms"
  | "glutes_hamstrings"
  | "quads_glutes"
  | "quads_calves"
  | "unilateral_lower";

export type ExperienceLevel = "beginner" | "intermediate" | "advanced";

export type EquipmentAccess =
  | "full_gym"
  | "dumbbells_only"
  | "barbell_rack"
  | "machines_only"
  | "bodyweight_only"
  | "minimal_home_gym";

export type ExerciseCategory = "main" | "accessory" | "isolation";

export type Muscle =
  | "chest"
  | "back"
  | "lats"
  | "upper_back"
  | "lower_back"
  | "shoulders"
  | "front_delts"
  | "side_delts"
  | "rear_delts"
  | "biceps"
  | "triceps"
  | "forearms"
  | "quads"
  | "glutes"
  | "hamstrings"
  | "calves"
  | "core";

export type MovementPattern =
  | "horizontal_press"
  | "vertical_press"
  | "horizontal_pull"
  | "vertical_pull"
  | "squat"
  | "hinge"
  | "lunge"
  | "curl"
  | "tricep_extension"
  | "fly"
  | "raise"
  | "calves"
  | "core"
  | "bodyweight_push"
  | "bodyweight_pull";

export type BiomechanicalPattern =
  | "compound_press"
  | "compound_pull"
  | "squat_pattern"
  | "hip_hinge"
  | "single_leg"
  | "knee_extension"
  | "knee_flexion"
  | "shoulder_abduction"
  | "rear_delt_isolation"
  | "elbow_flexion"
  | "elbow_extension"
  | "chest_fly"
  | "core_flexion"
  | "core_stability"
  | "calf_plantarflexion"
  | "hip_abduction"
  | "hip_adduction";

export type EquipmentType =
  | "barbell"
  | "dumbbell"
  | "kettlebell"
  | "cable"
  | "machine"
  | "bodyweight"
  | "smith"
  | "plate_loaded";

export type WorkoutTag =
  | "push"
  | "pull"
  | "full_body"
  | "upper"
  | "lower"
  | "female_friendly"
  | "glute_friendly"
  | "beginner_friendly"
  | "bodybuilding";

export type Laterality = "bilateral" | "unilateral";

export type FatigueCost = 1 | 2 | 3 | 4 | 5;
export type Complexity = 1 | 2 | 3 | 4 | 5;

export type JointArea = "shoulders" | "elbows" | "knees" | "lower_back" | "hips";
export type JointStress = "low" | "moderate" | "high";

export type ProgressionType =
  | "load_reps"
  | "reps_only"
  | "bodyweight_reps"
  | "assistance_reduction"
  | "time_hold";

export type MuscleEmphasis =
  | "upper_chest"
  | "mid_chest"
  | "lower_chest"
  | "lat_width"
  | "mid_back_thickness"
  | "upper_back_detail"
  | "quad_bias"
  | "glute_bias"
  | "hamstring_bias"
  | "front_delt_bias"
  | "side_delt_bias"
  | "rear_delt_bias"
  | "tricep_long_head"
  | "bicep_peak"
  | "core_stability";

export type WorkoutStyle =
  | "balanced"
  | "bodybuilding"
  | "high_volume"
  | "old_school_mass"
  | "intensity"
  | "pump"
  | "strength_size";

export type GeneratedWorkoutStyle =
  | "Balanced Training"
  | "Muscle Focus"
  | "High Volume"
  | "Heavy Volume"
  | "High Intensity"
  | "Short Rest Burn"
  | "Strength + Size";

export type VolumeTier = "moderate" | "high" | "brutal";

export type LiftRole =
  | "anchor"
  | "primary"
  | "secondary"
  | "accessory"
  | "isolation"
  | "finisher";

export type UnilateralBias = "none" | "optional" | "preferred" | "required";

export type EquipmentFit = "best" | "good" | "backup";

export type DifficultyTier = "beginner" | "intermediate" | "advanced";

export type Exercise = {
  id: string;
  name: string;
  primaryMuscle: Muscle;
  secondaryMuscles: Muscle[];
  category: ExerciseCategory;
  movementPattern: MovementPattern;
  biomechanicalPattern: BiomechanicalPattern;
  equipmentTypes: EquipmentType[];
  equipmentAccess: EquipmentAccess[];
  levels: ExperienceLevel[];
  workoutTags: WorkoutTag[];
  styleTags?: WorkoutStyle[];

  laterality: Laterality;
  fatigueCost: FatigueCost;
  complexity: Complexity;

  jointStress: JointStress;
  jointStressAreas: JointArea[];

  progressionType: ProgressionType;
  emphasis?: MuscleEmphasis[];

  isPrimaryCompound: boolean;
  isStable: boolean;

  sessionFocuses?: GeneratorFocus[];
  liftRole?: LiftRole;
  unilateralBias?: UnilateralBias;
  equipmentFit?: Partial<Record<EquipmentAccess, EquipmentFit>>;
  difficultyTier?: DifficultyTier;
};

export const exerciseLibrary: Exercise[] = [
  {
    id: "bench_press",
    name: "Bench Press",
    primaryMuscle: "chest",
    secondaryMuscles: ["front_delts", "triceps"],
    category: "main",
    movementPattern: "horizontal_press",
    biomechanicalPattern: "compound_press",
    equipmentTypes: ["barbell"],
    equipmentAccess: ["full_gym", "barbell_rack"],
    levels: ["intermediate", "advanced"],
    workoutTags: ["push", "upper", "full_body", "bodybuilding"],
    styleTags: ["strength_size", "old_school_mass", "balanced"],
    laterality: "bilateral",
    fatigueCost: 4,
    complexity: 4,
    jointStress: "moderate",
    jointStressAreas: ["shoulders", "elbows"],
    progressionType: "load_reps",
    emphasis: ["mid_chest"],
    isPrimaryCompound: true,
    isStable: false,
    sessionFocuses: ["chest", "push", "upper", "chest_triceps", "chest_shoulders"],
    liftRole: "anchor",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "best",
      barbell_rack: "best",
    },
    difficultyTier: "advanced",
  },
  {
    id: "incline_bench_press",
    name: "Incline Bench Press",
    primaryMuscle: "chest",
    secondaryMuscles: ["front_delts", "triceps"],
    category: "main",
    movementPattern: "horizontal_press",
    biomechanicalPattern: "compound_press",
    equipmentTypes: ["barbell"],
    equipmentAccess: ["full_gym", "barbell_rack"],
    levels: ["intermediate", "advanced"],
    workoutTags: ["push", "upper", "full_body", "bodybuilding"],
    styleTags: ["strength_size", "old_school_mass", "balanced", "bodybuilding"],
    laterality: "bilateral",
    fatigueCost: 4,
    complexity: 4,
    jointStress: "moderate",
    jointStressAreas: ["shoulders", "elbows"],
    progressionType: "load_reps",
    emphasis: ["upper_chest"],
    isPrimaryCompound: true,
    isStable: false,
    sessionFocuses: ["chest", "push", "upper", "chest_triceps", "chest_shoulders"],
    liftRole: "anchor",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "best",
      barbell_rack: "best",
    },
    difficultyTier: "advanced",
  },
  {
    id: "dumbbell_bench_press",
    name: "Dumbbell Bench Press",
    primaryMuscle: "chest",
    secondaryMuscles: ["front_delts", "triceps"],
    category: "main",
    movementPattern: "horizontal_press",
    biomechanicalPattern: "compound_press",
    equipmentTypes: ["dumbbell"],
    equipmentAccess: ["full_gym", "dumbbells_only", "minimal_home_gym"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: [
      "push",
      "upper",
      "full_body",
      "beginner_friendly",
      "female_friendly",
      "bodybuilding",
    ],
    styleTags: ["balanced", "bodybuilding", "old_school_mass", "strength_size"],
    laterality: "bilateral",
    fatigueCost: 3,
    complexity: 3,
    jointStress: "low",
    jointStressAreas: ["shoulders"],
    progressionType: "load_reps",
    emphasis: ["mid_chest"],
    isPrimaryCompound: true,
    isStable: false,
    sessionFocuses: ["chest", "push", "upper", "chest_triceps", "chest_shoulders"],
    liftRole: "anchor",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "good",
      dumbbells_only: "best",
      minimal_home_gym: "best",
    },
    difficultyTier: "intermediate",
  },
  {
    id: "incline_dumbbell_press",
    name: "Incline Dumbbell Press",
    primaryMuscle: "chest",
    secondaryMuscles: ["front_delts", "triceps"],
    category: "accessory",
    movementPattern: "horizontal_press",
    biomechanicalPattern: "compound_press",
    equipmentTypes: ["dumbbell"],
    equipmentAccess: ["full_gym", "dumbbells_only", "minimal_home_gym"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: [
      "push",
      "upper",
      "full_body",
      "beginner_friendly",
      "female_friendly",
      "bodybuilding",
    ],
    styleTags: ["bodybuilding", "high_volume", "balanced", "old_school_mass"],
    laterality: "bilateral",
    fatigueCost: 3,
    complexity: 3,
    jointStress: "low",
    jointStressAreas: ["shoulders"],
    progressionType: "load_reps",
    emphasis: ["upper_chest"],
    isPrimaryCompound: false,
    isStable: false,
    sessionFocuses: ["chest", "push", "upper", "chest_triceps", "chest_shoulders"],
    liftRole: "primary",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "best",
      dumbbells_only: "best",
      minimal_home_gym: "best",
    },
    difficultyTier: "intermediate",
  },
  {
    id: "incline_smith_press",
    name: "Incline Smith Press",
    primaryMuscle: "chest",
    secondaryMuscles: ["front_delts", "triceps"],
    category: "main",
    movementPattern: "horizontal_press",
    biomechanicalPattern: "compound_press",
    equipmentTypes: ["smith"],
    equipmentAccess: ["full_gym"],
    levels: ["intermediate", "advanced"],
    workoutTags: ["push", "upper", "bodybuilding"],
    styleTags: ["bodybuilding", "high_volume", "intensity", "pump"],
    laterality: "bilateral",
    fatigueCost: 3,
    complexity: 2,
    jointStress: "low",
    jointStressAreas: ["shoulders"],
    progressionType: "load_reps",
    emphasis: ["upper_chest"],
    isPrimaryCompound: true,
    isStable: true,
    sessionFocuses: ["chest", "push", "upper", "chest_triceps", "chest_shoulders"],
    liftRole: "anchor",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "best",
    },
    difficultyTier: "intermediate",
  },
  {
    id: "chest_press_machine",
    name: "Chest Press Machine",
    primaryMuscle: "chest",
    secondaryMuscles: ["front_delts", "triceps"],
    category: "main",
    movementPattern: "horizontal_press",
    biomechanicalPattern: "compound_press",
    equipmentTypes: ["machine"],
    equipmentAccess: ["full_gym", "machines_only"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: [
      "push",
      "upper",
      "full_body",
      "beginner_friendly",
      "female_friendly",
      "bodybuilding",
    ],
    styleTags: ["bodybuilding", "high_volume", "pump", "intensity", "balanced"],
    laterality: "bilateral",
    fatigueCost: 2,
    complexity: 1,
    jointStress: "low",
    jointStressAreas: ["shoulders"],
    progressionType: "load_reps",
    emphasis: ["mid_chest"],
    isPrimaryCompound: true,
    isStable: true,
    sessionFocuses: ["chest", "push", "upper", "chest_triceps", "chest_shoulders"],
    liftRole: "anchor",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "good",
      machines_only: "best",
    },
    difficultyTier: "beginner",
  },
  {
    id: "hammer_strength_chest_press",
    name: "Hammer Strength Chest Press",
    primaryMuscle: "chest",
    secondaryMuscles: ["front_delts", "triceps"],
    category: "main",
    movementPattern: "horizontal_press",
    biomechanicalPattern: "compound_press",
    equipmentTypes: ["plate_loaded"],
    equipmentAccess: ["full_gym"],
    levels: ["intermediate", "advanced"],
    workoutTags: ["push", "upper", "bodybuilding"],
    styleTags: ["bodybuilding", "high_volume", "old_school_mass", "pump"],
    laterality: "bilateral",
    fatigueCost: 3,
    complexity: 2,
    jointStress: "low",
    jointStressAreas: ["shoulders"],
    progressionType: "load_reps",
    emphasis: ["mid_chest"],
    isPrimaryCompound: true,
    isStable: true,
    sessionFocuses: ["chest", "push", "upper", "chest_triceps", "chest_shoulders"],
    liftRole: "anchor",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "best",
    },
    difficultyTier: "intermediate",
  },
  {
    id: "cable_fly",
    name: "Cable Fly",
    primaryMuscle: "chest",
    secondaryMuscles: ["front_delts"],
    category: "isolation",
    movementPattern: "fly",
    biomechanicalPattern: "chest_fly",
    equipmentTypes: ["cable"],
    equipmentAccess: ["full_gym"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: ["push", "upper", "female_friendly", "beginner_friendly", "bodybuilding"],
    styleTags: ["balanced", "bodybuilding", "high_volume", "pump"],
    laterality: "bilateral",
    fatigueCost: 1,
    complexity: 2,
    jointStress: "low",
    jointStressAreas: ["shoulders"],
    progressionType: "load_reps",
    emphasis: ["mid_chest"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["chest", "push", "upper", "chest_shoulders", "chest_triceps"],
    liftRole: "isolation",
    unilateralBias: "optional",
    equipmentFit: {
      full_gym: "best",
    },
    difficultyTier: "beginner",
  },
  {
    id: "low_to_high_cable_fly",
    name: "Low to High Cable Fly",
    primaryMuscle: "chest",
    secondaryMuscles: ["front_delts"],
    category: "isolation",
    movementPattern: "fly",
    biomechanicalPattern: "chest_fly",
    equipmentTypes: ["cable"],
    equipmentAccess: ["full_gym"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: ["push", "upper", "bodybuilding"],
    styleTags: ["bodybuilding", "high_volume", "pump"],
    laterality: "bilateral",
    fatigueCost: 1,
    complexity: 2,
    jointStress: "low",
    jointStressAreas: ["shoulders"],
    progressionType: "load_reps",
    emphasis: ["upper_chest"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["chest", "push", "upper", "chest_shoulders", "chest_triceps"],
    liftRole: "isolation",
    unilateralBias: "optional",
    equipmentFit: {
      full_gym: "best",
    },
    difficultyTier: "beginner",
  },
  {
    id: "pec_deck",
    name: "Pec Deck",
    primaryMuscle: "chest",
    secondaryMuscles: ["front_delts"],
    category: "isolation",
    movementPattern: "fly",
    biomechanicalPattern: "chest_fly",
    equipmentTypes: ["machine"],
    equipmentAccess: ["full_gym", "machines_only"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: [
      "push",
      "upper",
      "female_friendly",
      "beginner_friendly",
      "bodybuilding",
    ],
    styleTags: ["bodybuilding", "high_volume", "pump", "intensity"],
    laterality: "bilateral",
    fatigueCost: 1,
    complexity: 1,
    jointStress: "low",
    jointStressAreas: ["shoulders"],
    progressionType: "load_reps",
    emphasis: ["mid_chest"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["chest", "push", "upper", "chest_shoulders", "chest_triceps"],
    liftRole: "isolation",
    unilateralBias: "optional",
    equipmentFit: {
      full_gym: "good",
      machines_only: "best",
    },
    difficultyTier: "beginner",
  },
  {
    id: "push_ups",
    name: "Push-Ups",
    primaryMuscle: "chest",
    secondaryMuscles: ["front_delts", "triceps", "core"],
    category: "accessory",
    movementPattern: "bodyweight_push",
    biomechanicalPattern: "compound_press",
    equipmentTypes: ["bodyweight"],
    equipmentAccess: [
      "full_gym",
      "bodyweight_only",
      "minimal_home_gym",
      "dumbbells_only",
      "barbell_rack",
    ],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: ["push", "upper", "full_body", "beginner_friendly"],
    styleTags: ["pump", "high_volume", "bodybuilding", "balanced"],
    laterality: "bilateral",
    fatigueCost: 2,
    complexity: 1,
    jointStress: "low",
    jointStressAreas: ["shoulders"],
    progressionType: "bodyweight_reps",
    emphasis: ["mid_chest"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["chest", "push", "upper", "chest_triceps", "chest_shoulders", "full_body"],
    liftRole: "accessory",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "backup",
      bodyweight_only: "best",
      minimal_home_gym: "best",
      dumbbells_only: "good",
      barbell_rack: "good",
    },
    difficultyTier: "beginner",
  },

  {
    id: "barbell_row",
    name: "Barbell Row",
    primaryMuscle: "back",
    secondaryMuscles: ["lats", "upper_back", "biceps"],
    category: "main",
    movementPattern: "horizontal_pull",
    biomechanicalPattern: "compound_pull",
    equipmentTypes: ["barbell"],
    equipmentAccess: ["full_gym", "barbell_rack"],
    levels: ["intermediate", "advanced"],
    workoutTags: ["pull", "upper", "full_body", "bodybuilding"],
    styleTags: ["old_school_mass", "strength_size", "balanced"],
    laterality: "bilateral",
    fatigueCost: 4,
    complexity: 4,
    jointStress: "moderate",
    jointStressAreas: ["lower_back"],
    progressionType: "load_reps",
    emphasis: ["mid_back_thickness"],
    isPrimaryCompound: true,
    isStable: false,
    sessionFocuses: ["back", "pull", "upper", "back_biceps", "back_rear_delts"],
    liftRole: "anchor",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "best",
      barbell_rack: "best",
    },
    difficultyTier: "advanced",
  },
  {
    id: "lat_pulldown",
    name: "Lat Pulldown",
    primaryMuscle: "lats",
    secondaryMuscles: ["back", "biceps"],
    category: "main",
    movementPattern: "vertical_pull",
    biomechanicalPattern: "compound_pull",
    equipmentTypes: ["cable", "machine"],
    equipmentAccess: ["full_gym", "machines_only"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: [
      "pull",
      "upper",
      "full_body",
      "beginner_friendly",
      "female_friendly",
      "bodybuilding",
    ],
    styleTags: ["balanced", "bodybuilding", "high_volume", "pump"],
    laterality: "bilateral",
    fatigueCost: 2,
    complexity: 1,
    jointStress: "low",
    jointStressAreas: ["shoulders", "elbows"],
    progressionType: "load_reps",
    emphasis: ["lat_width"],
    isPrimaryCompound: true,
    isStable: true,
    sessionFocuses: ["back", "pull", "upper", "back_biceps", "back_rear_delts"],
    liftRole: "anchor",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "best",
      machines_only: "best",
    },
    difficultyTier: "beginner",
  },
  {
    id: "wide_grip_lat_pulldown",
    name: "Wide Grip Lat Pulldown",
    primaryMuscle: "lats",
    secondaryMuscles: ["upper_back", "biceps"],
    category: "accessory",
    movementPattern: "vertical_pull",
    biomechanicalPattern: "compound_pull",
    equipmentTypes: ["cable", "machine"],
    equipmentAccess: ["full_gym", "machines_only"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: ["pull", "upper", "bodybuilding"],
    styleTags: ["bodybuilding", "high_volume", "pump"],
    laterality: "bilateral",
    fatigueCost: 2,
    complexity: 1,
    jointStress: "low",
    jointStressAreas: ["shoulders", "elbows"],
    progressionType: "load_reps",
    emphasis: ["lat_width"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["back", "pull", "upper", "back_biceps"],
    liftRole: "primary",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "good",
      machines_only: "best",
    },
    difficultyTier: "beginner",
  },
  {
    id: "seated_cable_row",
    name: "Seated Cable Row",
    primaryMuscle: "back",
    secondaryMuscles: ["lats", "upper_back", "biceps"],
    category: "accessory",
    movementPattern: "horizontal_pull",
    biomechanicalPattern: "compound_pull",
    equipmentTypes: ["cable", "machine"],
    equipmentAccess: ["full_gym", "machines_only"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: [
      "pull",
      "upper",
      "full_body",
      "beginner_friendly",
      "female_friendly",
      "bodybuilding",
    ],
    styleTags: ["balanced", "bodybuilding", "pump", "high_volume"],
    laterality: "bilateral",
    fatigueCost: 2,
    complexity: 1,
    jointStress: "low",
    jointStressAreas: ["elbows"],
    progressionType: "load_reps",
    emphasis: ["mid_back_thickness"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["back", "pull", "upper", "back_biceps", "back_rear_delts"],
    liftRole: "primary",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "best",
      machines_only: "best",
    },
    difficultyTier: "beginner",
  },
  {
    id: "chest_supported_row",
    name: "Chest Supported Row",
    primaryMuscle: "upper_back",
    secondaryMuscles: ["back", "lats", "biceps"],
    category: "accessory",
    movementPattern: "horizontal_pull",
    biomechanicalPattern: "compound_pull",
    equipmentTypes: ["machine", "plate_loaded"],
    equipmentAccess: ["full_gym"],
    levels: ["intermediate", "advanced"],
    workoutTags: ["pull", "upper", "bodybuilding"],
    styleTags: ["bodybuilding", "high_volume", "pump"],
    laterality: "bilateral",
    fatigueCost: 2,
    complexity: 1,
    jointStress: "low",
    jointStressAreas: [],
    progressionType: "load_reps",
    emphasis: ["mid_back_thickness", "upper_back_detail"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["back", "pull", "upper", "back_biceps", "back_rear_delts"],
    liftRole: "primary",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "best",
    },
    difficultyTier: "beginner",
  },
  {
    id: "single_arm_dumbbell_row",
    name: "Single Arm Dumbbell Row",
    primaryMuscle: "back",
    secondaryMuscles: ["lats", "upper_back", "biceps"],
    category: "accessory",
    movementPattern: "horizontal_pull",
    biomechanicalPattern: "compound_pull",
    equipmentTypes: ["dumbbell"],
    equipmentAccess: ["full_gym", "dumbbells_only", "minimal_home_gym"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: ["pull", "upper", "full_body", "beginner_friendly"],
    styleTags: ["balanced", "bodybuilding", "old_school_mass"],
    laterality: "unilateral",
    fatigueCost: 2,
    complexity: 2,
    jointStress: "low",
    jointStressAreas: ["lower_back"],
    progressionType: "load_reps",
    emphasis: ["mid_back_thickness"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["back", "pull", "upper", "back_biceps", "back_rear_delts"],
    liftRole: "secondary",
    unilateralBias: "preferred",
    equipmentFit: {
      full_gym: "good",
      dumbbells_only: "best",
      minimal_home_gym: "best",
    },
    difficultyTier: "beginner",
  },
  {
    id: "straight_arm_pulldown",
    name: "Straight Arm Pulldown",
    primaryMuscle: "lats",
    secondaryMuscles: ["core"],
    category: "isolation",
    movementPattern: "vertical_pull",
    biomechanicalPattern: "compound_pull",
    equipmentTypes: ["cable"],
    equipmentAccess: ["full_gym"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: ["pull", "upper", "bodybuilding"],
    styleTags: ["bodybuilding", "pump", "high_volume"],
    laterality: "bilateral",
    fatigueCost: 1,
    complexity: 1,
    jointStress: "low",
    jointStressAreas: ["shoulders"],
    progressionType: "load_reps",
    emphasis: ["lat_width"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["back", "pull", "upper", "back_biceps"],
    liftRole: "isolation",
    unilateralBias: "optional",
    equipmentFit: {
      full_gym: "best",
    },
    difficultyTier: "beginner",
  },

  {
    id: "back_squat",
    name: "Back Squat",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "hamstrings", "core"],
    category: "main",
    movementPattern: "squat",
    biomechanicalPattern: "squat_pattern",
    equipmentTypes: ["barbell"],
    equipmentAccess: ["full_gym", "barbell_rack"],
    levels: ["intermediate", "advanced"],
    workoutTags: ["lower", "full_body"],
    styleTags: ["strength_size", "old_school_mass", "balanced"],
    laterality: "bilateral",
    fatigueCost: 5,
    complexity: 4,
    jointStress: "moderate",
    jointStressAreas: ["knees", "lower_back", "hips"],
    progressionType: "load_reps",
    emphasis: ["quad_bias"],
    isPrimaryCompound: true,
    isStable: false,
    sessionFocuses: ["legs", "lower", "quads_glutes", "quads_calves", "full_body"],
    liftRole: "anchor",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "best",
      barbell_rack: "best",
    },
    difficultyTier: "advanced",
  },
  {
    id: "bulgarian_split_squat",
    name: "Bulgarian Split Squat",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "hamstrings"],
    category: "accessory",
    movementPattern: "lunge",
    biomechanicalPattern: "single_leg",
    equipmentTypes: ["dumbbell", "bodyweight"],
    equipmentAccess: ["full_gym", "dumbbells_only", "minimal_home_gym", "bodyweight_only"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: [
      "lower",
      "full_body",
      "glute_friendly",
      "bodybuilding",
      "female_friendly",
    ],
    styleTags: ["balanced", "bodybuilding", "high_volume", "pump", "old_school_mass"],
    laterality: "unilateral",
    fatigueCost: 3,
    complexity: 2,
    jointStress: "moderate",
    jointStressAreas: ["knees", "hips"],
    progressionType: "load_reps",
    emphasis: ["quad_bias", "glute_bias"],
    isPrimaryCompound: false,
    isStable: false,
    sessionFocuses: ["legs", "lower", "quads_glutes", "glutes_hamstrings", "unilateral_lower"],
    liftRole: "primary",
    unilateralBias: "preferred",
    equipmentFit: {
      full_gym: "best",
      dumbbells_only: "best",
      minimal_home_gym: "best",
      bodyweight_only: "good",
    },
    difficultyTier: "intermediate",
  },
  {
    id: "reverse_lunge",
    name: "Reverse Lunge",
    primaryMuscle: "glutes",
    secondaryMuscles: ["quads", "hamstrings"],
    category: "accessory",
    movementPattern: "lunge",
    biomechanicalPattern: "single_leg",
    equipmentTypes: ["dumbbell", "bodyweight", "smith"],
    equipmentAccess: ["full_gym", "dumbbells_only", "minimal_home_gym", "bodyweight_only"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: ["lower", "full_body", "glute_friendly", "female_friendly"],
    styleTags: ["balanced", "bodybuilding", "high_volume", "pump"],
    laterality: "unilateral",
    fatigueCost: 3,
    complexity: 2,
    jointStress: "low",
    jointStressAreas: ["knees", "hips"],
    progressionType: "load_reps",
    emphasis: ["glute_bias"],
    isPrimaryCompound: false,
    isStable: false,
    sessionFocuses: ["legs", "lower", "glutes_hamstrings", "quads_glutes", "unilateral_lower"],
    liftRole: "primary",
    unilateralBias: "preferred",
    equipmentFit: {
      full_gym: "best",
      dumbbells_only: "best",
      minimal_home_gym: "best",
      bodyweight_only: "good",
    },
    difficultyTier: "beginner",
  },
  {
    id: "step_up",
    name: "Step-Up",
    primaryMuscle: "glutes",
    secondaryMuscles: ["quads", "hamstrings"],
    category: "accessory",
    movementPattern: "lunge",
    biomechanicalPattern: "single_leg",
    equipmentTypes: ["dumbbell", "bodyweight"],
    equipmentAccess: ["full_gym", "dumbbells_only", "minimal_home_gym", "bodyweight_only"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: ["lower", "full_body", "glute_friendly", "female_friendly"],
    styleTags: ["balanced", "bodybuilding", "high_volume"],
    laterality: "unilateral",
    fatigueCost: 2,
    complexity: 2,
    jointStress: "low",
    jointStressAreas: ["knees", "hips"],
    progressionType: "load_reps",
    emphasis: ["glute_bias", "quad_bias"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["legs", "lower", "glutes_hamstrings", "quads_glutes", "unilateral_lower"],
    liftRole: "secondary",
    unilateralBias: "preferred",
    equipmentFit: {
      full_gym: "good",
      dumbbells_only: "best",
      minimal_home_gym: "best",
      bodyweight_only: "good",
    },
    difficultyTier: "beginner",
  },
  {
    id: "hip_thrust",
    name: "Hip Thrust",
    primaryMuscle: "glutes",
    secondaryMuscles: ["hamstrings", "core"],
    category: "main",
    movementPattern: "hinge",
    biomechanicalPattern: "hip_hinge",
    equipmentTypes: ["barbell", "dumbbell", "smith"],
    equipmentAccess: ["full_gym", "barbell_rack", "dumbbells_only", "minimal_home_gym"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: ["lower", "glute_friendly", "female_friendly", "bodybuilding"],
    styleTags: ["bodybuilding", "high_volume", "pump", "balanced", "strength_size"],
    laterality: "bilateral",
    fatigueCost: 3,
    complexity: 2,
    jointStress: "low",
    jointStressAreas: ["hips"],
    progressionType: "load_reps",
    emphasis: ["glute_bias"],
    isPrimaryCompound: true,
    isStable: true,
    sessionFocuses: ["legs", "lower", "glutes_hamstrings", "quads_glutes", "unilateral_lower"],
    liftRole: "anchor",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "best",
      barbell_rack: "best",
      dumbbells_only: "good",
      minimal_home_gym: "good",
    },
    difficultyTier: "beginner",
  },
  {
    id: "glute_bridge",
    name: "Glute Bridge",
    primaryMuscle: "glutes",
    secondaryMuscles: ["hamstrings", "core"],
    category: "accessory",
    movementPattern: "hinge",
    biomechanicalPattern: "hip_hinge",
    equipmentTypes: ["bodyweight", "dumbbell", "barbell"],
    equipmentAccess: [
      "full_gym",
      "dumbbells_only",
      "minimal_home_gym",
      "bodyweight_only",
      "barbell_rack",
    ],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: ["lower", "glute_friendly", "female_friendly"],
    styleTags: ["balanced", "bodybuilding", "pump", "high_volume"],
    laterality: "bilateral",
    fatigueCost: 2,
    complexity: 1,
    jointStress: "low",
    jointStressAreas: ["hips"],
    progressionType: "load_reps",
    emphasis: ["glute_bias"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["legs", "lower", "glutes_hamstrings", "unilateral_lower"],
    liftRole: "secondary",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "good",
      dumbbells_only: "good",
      minimal_home_gym: "best",
      bodyweight_only: "best",
      barbell_rack: "good",
    },
    difficultyTier: "beginner",
  },
  {
    id: "smith_squat",
    name: "Smith Squat",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes"],
    category: "main",
    movementPattern: "squat",
    biomechanicalPattern: "squat_pattern",
    equipmentTypes: ["smith"],
    equipmentAccess: ["full_gym"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: ["lower", "bodybuilding", "female_friendly"],
    styleTags: ["bodybuilding", "high_volume", "pump", "strength_size"],
    laterality: "bilateral",
    fatigueCost: 3,
    complexity: 1,
    jointStress: "moderate",
    jointStressAreas: ["knees", "hips"],
    progressionType: "load_reps",
    emphasis: ["quad_bias"],
    isPrimaryCompound: true,
    isStable: true,
    sessionFocuses: ["legs", "lower", "quads_glutes", "quads_calves"],
    liftRole: "anchor",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "best",
    },
    difficultyTier: "beginner",
  },
  {
    id: "smith_reverse_lunge",
    name: "Smith Reverse Lunge",
    primaryMuscle: "glutes",
    secondaryMuscles: ["quads", "hamstrings"],
    category: "accessory",
    movementPattern: "lunge",
    biomechanicalPattern: "single_leg",
    equipmentTypes: ["smith"],
    equipmentAccess: ["full_gym"],
    levels: ["intermediate", "advanced"],
    workoutTags: ["lower", "glute_friendly", "female_friendly", "bodybuilding"],
    styleTags: ["bodybuilding", "high_volume", "pump"],
    laterality: "unilateral",
    fatigueCost: 3,
    complexity: 2,
    jointStress: "low",
    jointStressAreas: ["knees", "hips"],
    progressionType: "load_reps",
    emphasis: ["glute_bias"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["legs", "lower", "glutes_hamstrings", "quads_glutes", "unilateral_lower"],
    liftRole: "primary",
    unilateralBias: "preferred",
    equipmentFit: {
      full_gym: "best",
    },
    difficultyTier: "intermediate",
  },
  {
    id: "single_leg_rdl",
    name: "Single Leg Romanian Deadlift",
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["glutes", "core"],
    category: "accessory",
    movementPattern: "hinge",
    biomechanicalPattern: "single_leg",
    equipmentTypes: ["dumbbell", "bodyweight"],
    equipmentAccess: ["full_gym", "dumbbells_only", "minimal_home_gym", "bodyweight_only"],
    levels: ["intermediate", "advanced"],
    workoutTags: ["lower", "glute_friendly", "female_friendly"],
    styleTags: ["balanced", "bodybuilding", "high_volume"],
    laterality: "unilateral",
    fatigueCost: 2,
    complexity: 3,
    jointStress: "low",
    jointStressAreas: ["hips"],
    progressionType: "load_reps",
    emphasis: ["hamstring_bias", "glute_bias"],
    isPrimaryCompound: false,
    isStable: false,
    sessionFocuses: ["legs", "lower", "glutes_hamstrings", "unilateral_lower"],
    liftRole: "secondary",
    unilateralBias: "preferred",
    equipmentFit: {
      full_gym: "good",
      dumbbells_only: "best",
      minimal_home_gym: "best",
      bodyweight_only: "backup",
    },
    difficultyTier: "advanced",
  },
  {
    id: "seated_leg_curl",
    name: "Seated Leg Curl",
    primaryMuscle: "hamstrings",
    secondaryMuscles: [],
    category: "isolation",
    movementPattern: "hinge",
    biomechanicalPattern: "knee_flexion",
    equipmentTypes: ["machine"],
    equipmentAccess: ["full_gym", "machines_only"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: ["lower", "bodybuilding", "female_friendly", "glute_friendly"],
    styleTags: ["bodybuilding", "high_volume", "pump", "intensity"],
    laterality: "bilateral",
    fatigueCost: 1,
    complexity: 1,
    jointStress: "low",
    jointStressAreas: ["knees"],
    progressionType: "load_reps",
    emphasis: ["hamstring_bias"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["legs", "lower", "glutes_hamstrings"],
    liftRole: "isolation",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "good",
      machines_only: "best",
    },
    difficultyTier: "beginner",
  },
  {
    id: "lying_leg_curl",
    name: "Lying Leg Curl",
    primaryMuscle: "hamstrings",
    secondaryMuscles: [],
    category: "isolation",
    movementPattern: "hinge",
    biomechanicalPattern: "knee_flexion",
    equipmentTypes: ["machine"],
    equipmentAccess: ["full_gym", "machines_only"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: ["lower", "bodybuilding", "female_friendly", "glute_friendly"],
    styleTags: ["bodybuilding", "high_volume", "pump", "intensity"],
    laterality: "bilateral",
    fatigueCost: 1,
    complexity: 1,
    jointStress: "low",
    jointStressAreas: ["knees"],
    progressionType: "load_reps",
    emphasis: ["hamstring_bias"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["legs", "lower", "glutes_hamstrings"],
    liftRole: "isolation",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "good",
      machines_only: "best",
    },
    difficultyTier: "beginner",
  },
  {
    id: "seated_calf_raise",
    name: "Seated Calf Raise",
    primaryMuscle: "calves",
    secondaryMuscles: [],
    category: "isolation",
    movementPattern: "calves",
    biomechanicalPattern: "calf_plantarflexion",
    equipmentTypes: ["machine", "plate_loaded"],
    equipmentAccess: ["full_gym", "machines_only"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: ["lower", "bodybuilding"],
    styleTags: ["balanced", "bodybuilding", "high_volume", "pump"],
    laterality: "bilateral",
    fatigueCost: 1,
    complexity: 1,
    jointStress: "low",
    jointStressAreas: [],
    progressionType: "load_reps",
    emphasis: [],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["legs", "lower", "quads_calves"],
    liftRole: "isolation",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "good",
      machines_only: "best",
    },
    difficultyTier: "beginner",
  },
  {
    id: "cable_kickback",
    name: "Cable Kickback",
    primaryMuscle: "glutes",
    secondaryMuscles: [],
    category: "isolation",
    movementPattern: "hinge",
    biomechanicalPattern: "hip_hinge",
    equipmentTypes: ["cable"],
    equipmentAccess: ["full_gym"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: ["lower", "glute_friendly", "female_friendly", "bodybuilding"],
    styleTags: ["bodybuilding", "pump", "high_volume"],
    laterality: "unilateral",
    fatigueCost: 1,
    complexity: 1,
    jointStress: "low",
    jointStressAreas: ["hips"],
    progressionType: "load_reps",
    emphasis: ["glute_bias"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["legs", "lower", "glutes_hamstrings", "unilateral_lower"],
    liftRole: "isolation",
    unilateralBias: "preferred",
    equipmentFit: {
      full_gym: "best",
    },
    difficultyTier: "beginner",
  },
  {
    id: "hip_abduction_machine",
    name: "Hip Abduction Machine",
    primaryMuscle: "glutes",
    secondaryMuscles: [],
    category: "isolation",
    movementPattern: "raise",
    biomechanicalPattern: "hip_abduction",
    equipmentTypes: ["machine"],
    equipmentAccess: ["full_gym", "machines_only"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: ["lower", "glute_friendly", "female_friendly", "bodybuilding"],
    styleTags: ["bodybuilding", "pump", "high_volume", "intensity"],
    laterality: "bilateral",
    fatigueCost: 1,
    complexity: 1,
    jointStress: "low",
    jointStressAreas: ["hips"],
    progressionType: "load_reps",
    emphasis: ["glute_bias"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["legs", "lower", "glutes_hamstrings"],
    liftRole: "isolation",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "good",
      machines_only: "best",
    },
    difficultyTier: "beginner",
  },
  {
    id: "hip_adduction_machine",
    name: "Hip Adduction Machine",
    primaryMuscle: "glutes",
    secondaryMuscles: ["quads"],
    category: "isolation",
    movementPattern: "raise",
    biomechanicalPattern: "hip_adduction",
    equipmentTypes: ["machine"],
    equipmentAccess: ["full_gym", "machines_only"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: ["lower", "female_friendly", "bodybuilding"],
    styleTags: ["bodybuilding", "pump", "high_volume"],
    laterality: "bilateral",
    fatigueCost: 1,
    complexity: 1,
    jointStress: "low",
    jointStressAreas: ["hips"],
    progressionType: "load_reps",
    emphasis: ["glute_bias"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["legs", "lower", "glutes_hamstrings", "quads_glutes"],
    liftRole: "isolation",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "good",
      machines_only: "best",
    },
    difficultyTier: "beginner",
  },
  {
    id: "frog_pumps",
    name: "Frog Pumps",
    primaryMuscle: "glutes",
    secondaryMuscles: [],
    category: "isolation",
    movementPattern: "hinge",
    biomechanicalPattern: "hip_hinge",
    equipmentTypes: ["bodyweight", "dumbbell"],
    equipmentAccess: ["full_gym", "dumbbells_only", "minimal_home_gym", "bodyweight_only"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: ["lower", "glute_friendly", "female_friendly"],
    styleTags: ["pump", "high_volume", "bodybuilding"],
    laterality: "bilateral",
    fatigueCost: 1,
    complexity: 1,
    jointStress: "low",
    jointStressAreas: ["hips"],
    progressionType: "bodyweight_reps",
    emphasis: ["glute_bias"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["legs", "lower", "glutes_hamstrings"],
    liftRole: "finisher",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "backup",
      dumbbells_only: "good",
      minimal_home_gym: "best",
      bodyweight_only: "best",
    },
    difficultyTier: "beginner",
  },
  {
    id: "sumo_dumbbell_squat",
    name: "Sumo Dumbbell Squat",
    primaryMuscle: "glutes",
    secondaryMuscles: ["quads", "hamstrings"],
    category: "accessory",
    movementPattern: "squat",
    biomechanicalPattern: "squat_pattern",
    equipmentTypes: ["dumbbell", "kettlebell"],
    equipmentAccess: ["full_gym", "dumbbells_only", "minimal_home_gym"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: ["lower", "glute_friendly", "female_friendly"],
    styleTags: ["balanced", "bodybuilding", "high_volume"],
    laterality: "bilateral",
    fatigueCost: 2,
    complexity: 1,
    jointStress: "low",
    jointStressAreas: ["hips", "knees"],
    progressionType: "load_reps",
    emphasis: ["glute_bias"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["legs", "lower", "glutes_hamstrings", "quads_glutes"],
    liftRole: "secondary",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "good",
      dumbbells_only: "best",
      minimal_home_gym: "best",
    },
    difficultyTier: "beginner",
  },
  {
    id: "hack_squat",
    name: "Hack Squat",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes"],
    category: "main",
    movementPattern: "squat",
    biomechanicalPattern: "squat_pattern",
    equipmentTypes: ["machine"],
    equipmentAccess: ["full_gym", "machines_only"],
    levels: ["intermediate", "advanced"],
    workoutTags: ["lower", "bodybuilding"],
    styleTags: ["bodybuilding", "high_volume", "old_school_mass"],
    laterality: "bilateral",
    fatigueCost: 3,
    complexity: 1,
    jointStress: "moderate",
    jointStressAreas: ["knees", "hips"],
    progressionType: "load_reps",
    emphasis: ["quad_bias"],
    isPrimaryCompound: true,
    isStable: true,
    sessionFocuses: ["legs", "lower", "quads_glutes", "quads_calves"],
    liftRole: "anchor",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "best",
      machines_only: "best",
    },
    difficultyTier: "intermediate",
  },
  {
    id: "goblet_squat",
    name: "Goblet Squat",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "core"],
    category: "accessory",
    movementPattern: "squat",
    biomechanicalPattern: "squat_pattern",
    equipmentTypes: ["dumbbell", "kettlebell"],
    equipmentAccess: ["full_gym", "dumbbells_only", "minimal_home_gym"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: ["lower", "full_body", "beginner_friendly", "female_friendly"],
    styleTags: ["balanced"],
    laterality: "bilateral",
    fatigueCost: 2,
    complexity: 2,
    jointStress: "low",
    jointStressAreas: ["knees", "hips"],
    progressionType: "load_reps",
    emphasis: ["quad_bias"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["legs", "lower", "quads_glutes", "full_body"],
    liftRole: "secondary",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "backup",
      dumbbells_only: "best",
      minimal_home_gym: "best",
    },
    difficultyTier: "beginner",
  },
  {
    id: "leg_press",
    name: "Leg Press",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "hamstrings"],
    category: "main",
    movementPattern: "squat",
    biomechanicalPattern: "squat_pattern",
    equipmentTypes: ["machine"],
    equipmentAccess: ["full_gym", "machines_only"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: [
      "lower",
      "full_body",
      "beginner_friendly",
      "female_friendly",
      "bodybuilding",
    ],
    styleTags: ["bodybuilding", "high_volume", "pump", "balanced"],
    laterality: "bilateral",
    fatigueCost: 3,
    complexity: 1,
    jointStress: "moderate",
    jointStressAreas: ["knees", "hips"],
    progressionType: "load_reps",
    emphasis: ["quad_bias"],
    isPrimaryCompound: true,
    isStable: true,
    sessionFocuses: ["legs", "lower", "quads_glutes", "quads_calves"],
    liftRole: "anchor",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "good",
      machines_only: "best",
    },
    difficultyTier: "beginner",
  },
  {
    id: "walking_lunges",
    name: "Walking Lunges",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "hamstrings"],
    category: "accessory",
    movementPattern: "lunge",
    biomechanicalPattern: "single_leg",
    equipmentTypes: ["dumbbell", "bodyweight"],
    equipmentAccess: ["full_gym", "dumbbells_only", "bodyweight_only", "minimal_home_gym"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: ["lower", "full_body", "glute_friendly"],
    styleTags: ["balanced", "bodybuilding", "old_school_mass"],
    laterality: "unilateral",
    fatigueCost: 3,
    complexity: 2,
    jointStress: "moderate",
    jointStressAreas: ["knees", "hips"],
    progressionType: "load_reps",
    emphasis: ["quad_bias", "glute_bias"],
    isPrimaryCompound: false,
    isStable: false,
    sessionFocuses: ["legs", "lower", "quads_glutes", "glutes_hamstrings", "unilateral_lower"],
    liftRole: "secondary",
    unilateralBias: "preferred",
    equipmentFit: {
      full_gym: "good",
      dumbbells_only: "best",
      bodyweight_only: "good",
      minimal_home_gym: "best",
    },
    difficultyTier: "intermediate",
  },
  {
    id: "leg_extension",
    name: "Leg Extension",
    primaryMuscle: "quads",
    secondaryMuscles: [],
    category: "isolation",
    movementPattern: "squat",
    biomechanicalPattern: "knee_extension",
    equipmentTypes: ["machine"],
    equipmentAccess: ["full_gym", "machines_only"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: ["lower", "beginner_friendly", "female_friendly", "bodybuilding"],
    styleTags: ["bodybuilding", "high_volume", "pump", "intensity"],
    laterality: "bilateral",
    fatigueCost: 1,
    complexity: 1,
    jointStress: "moderate",
    jointStressAreas: ["knees"],
    progressionType: "load_reps",
    emphasis: ["quad_bias"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["legs", "lower", "quads_glutes", "quads_calves"],
    liftRole: "isolation",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "good",
      machines_only: "best",
    },
    difficultyTier: "beginner",
  },
  {
    id: "romanian_deadlift",
    name: "Romanian Deadlift",
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["glutes", "lower_back"],
    category: "main",
    movementPattern: "hinge",
    biomechanicalPattern: "hip_hinge",
    equipmentTypes: ["barbell", "dumbbell"],
    equipmentAccess: ["full_gym", "barbell_rack", "dumbbells_only", "minimal_home_gym"],
    levels: ["intermediate", "advanced"],
    workoutTags: ["lower", "full_body", "glute_friendly"],
    styleTags: ["strength_size", "old_school_mass", "balanced"],
    laterality: "bilateral",
    fatigueCost: 4,
    complexity: 3,
    jointStress: "moderate",
    jointStressAreas: ["lower_back", "hips"],
    progressionType: "load_reps",
    emphasis: ["hamstring_bias", "glute_bias"],
    isPrimaryCompound: true,
    isStable: false,
    sessionFocuses: ["legs", "lower", "glutes_hamstrings", "full_body"],
    liftRole: "anchor",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "best",
      barbell_rack: "best",
      dumbbells_only: "good",
      minimal_home_gym: "good",
    },
    difficultyTier: "advanced",
  },
  {
    id: "hamstring_curl",
    name: "Hamstring Curl",
    primaryMuscle: "hamstrings",
    secondaryMuscles: [],
    category: "isolation",
    movementPattern: "hinge",
    biomechanicalPattern: "knee_flexion",
    equipmentTypes: ["machine"],
    equipmentAccess: ["full_gym", "machines_only"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: [
      "lower",
      "beginner_friendly",
      "female_friendly",
      "glute_friendly",
      "bodybuilding",
    ],
    styleTags: ["bodybuilding", "high_volume", "pump"],
    laterality: "bilateral",
    fatigueCost: 1,
    complexity: 1,
    jointStress: "low",
    jointStressAreas: ["knees"],
    progressionType: "load_reps",
    emphasis: ["hamstring_bias"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["legs", "lower", "glutes_hamstrings"],
    liftRole: "isolation",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "good",
      machines_only: "best",
    },
    difficultyTier: "beginner",
  },
  {
    id: "standing_calf_raise",
    name: "Standing Calf Raise",
    primaryMuscle: "calves",
    secondaryMuscles: [],
    category: "isolation",
    movementPattern: "calves",
    biomechanicalPattern: "calf_plantarflexion",
    equipmentTypes: ["machine", "bodyweight"],
    equipmentAccess: ["full_gym", "machines_only", "bodyweight_only"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: ["lower", "bodybuilding"],
    styleTags: ["balanced", "bodybuilding", "high_volume", "pump"],
    laterality: "bilateral",
    fatigueCost: 1,
    complexity: 1,
    jointStress: "low",
    jointStressAreas: [],
    progressionType: "load_reps",
    emphasis: [],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["legs", "lower", "quads_calves"],
    liftRole: "isolation",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "good",
      machines_only: "good",
      bodyweight_only: "best",
    },
    difficultyTier: "beginner",
  },

  {
    id: "overhead_press",
    name: "Overhead Press",
    primaryMuscle: "shoulders",
    secondaryMuscles: ["front_delts", "triceps", "core"],
    category: "main",
    movementPattern: "vertical_press",
    biomechanicalPattern: "compound_press",
    equipmentTypes: ["barbell"],
    equipmentAccess: ["full_gym", "barbell_rack"],
    levels: ["intermediate", "advanced"],
    workoutTags: ["push", "upper", "full_body"],
    styleTags: ["strength_size", "old_school_mass", "balanced"],
    laterality: "bilateral",
    fatigueCost: 4,
    complexity: 4,
    jointStress: "moderate",
    jointStressAreas: ["shoulders", "lower_back"],
    progressionType: "load_reps",
    emphasis: ["front_delt_bias"],
    isPrimaryCompound: true,
    isStable: false,
    sessionFocuses: ["shoulders", "push", "upper", "shoulders_arms", "chest_shoulders"],
    liftRole: "anchor",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "best",
      barbell_rack: "best",
    },
    difficultyTier: "advanced",
  },
  {
    id: "seated_dumbbell_press",
    name: "Seated Dumbbell Press",
    primaryMuscle: "shoulders",
    secondaryMuscles: ["front_delts", "triceps"],
    category: "main",
    movementPattern: "vertical_press",
    biomechanicalPattern: "compound_press",
    equipmentTypes: ["dumbbell"],
    equipmentAccess: ["full_gym", "dumbbells_only", "minimal_home_gym"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: [
      "push",
      "upper",
      "full_body",
      "beginner_friendly",
      "female_friendly",
      "bodybuilding",
    ],
    styleTags: ["balanced", "bodybuilding", "old_school_mass"],
    laterality: "bilateral",
    fatigueCost: 3,
    complexity: 2,
    jointStress: "low",
    jointStressAreas: ["shoulders"],
    progressionType: "load_reps",
    emphasis: ["front_delt_bias"],
    isPrimaryCompound: true,
    isStable: true,
    sessionFocuses: ["shoulders", "push", "upper", "shoulders_arms", "chest_shoulders"],
    liftRole: "anchor",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "good",
      dumbbells_only: "best",
      minimal_home_gym: "best",
    },
    difficultyTier: "beginner",
  },
  {
    id: "machine_shoulder_press",
    name: "Machine Shoulder Press",
    primaryMuscle: "shoulders",
    secondaryMuscles: ["front_delts", "triceps"],
    category: "accessory",
    movementPattern: "vertical_press",
    biomechanicalPattern: "compound_press",
    equipmentTypes: ["machine"],
    equipmentAccess: ["full_gym", "machines_only"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: ["push", "upper", "bodybuilding"],
    styleTags: ["bodybuilding", "high_volume", "pump", "intensity"],
    laterality: "bilateral",
    fatigueCost: 2,
    complexity: 1,
    jointStress: "low",
    jointStressAreas: ["shoulders"],
    progressionType: "load_reps",
    emphasis: ["front_delt_bias"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["shoulders", "push", "upper", "shoulders_arms", "chest_shoulders"],
    liftRole: "primary",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "good",
      machines_only: "best",
    },
    difficultyTier: "beginner",
  },
  {
    id: "lateral_raises",
    name: "Lateral Raises",
    primaryMuscle: "side_delts",
    secondaryMuscles: ["shoulders"],
    category: "isolation",
    movementPattern: "raise",
    biomechanicalPattern: "shoulder_abduction",
    equipmentTypes: ["dumbbell"],
    equipmentAccess: ["full_gym", "dumbbells_only", "minimal_home_gym"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: [
      "push",
      "upper",
      "full_body",
      "female_friendly",
      "beginner_friendly",
      "bodybuilding",
    ],
    styleTags: ["bodybuilding", "pump", "high_volume", "intensity"],
    laterality: "bilateral",
    fatigueCost: 1,
    complexity: 1,
    jointStress: "low",
    jointStressAreas: ["shoulders"],
    progressionType: "load_reps",
    emphasis: ["side_delt_bias"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["shoulders", "push", "upper", "shoulders_arms", "chest_shoulders"],
    liftRole: "isolation",
    unilateralBias: "optional",
    equipmentFit: {
      full_gym: "good",
      dumbbells_only: "best",
      minimal_home_gym: "best",
    },
    difficultyTier: "beginner",
  },
  {
    id: "cable_lateral_raise",
    name: "Cable Lateral Raise",
    primaryMuscle: "side_delts",
    secondaryMuscles: ["shoulders"],
    category: "isolation",
    movementPattern: "raise",
    biomechanicalPattern: "shoulder_abduction",
    equipmentTypes: ["cable"],
    equipmentAccess: ["full_gym"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: ["push", "upper", "bodybuilding"],
    styleTags: ["bodybuilding", "pump", "high_volume"],
    laterality: "unilateral",
    fatigueCost: 1,
    complexity: 1,
    jointStress: "low",
    jointStressAreas: ["shoulders"],
    progressionType: "load_reps",
    emphasis: ["side_delt_bias"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["shoulders", "push", "upper", "shoulders_arms", "chest_shoulders"],
    liftRole: "isolation",
    unilateralBias: "preferred",
    equipmentFit: {
      full_gym: "best",
    },
    difficultyTier: "beginner",
  },
  {
    id: "rear_delt_fly",
    name: "Rear Delt Fly",
    primaryMuscle: "rear_delts",
    secondaryMuscles: ["upper_back"],
    category: "isolation",
    movementPattern: "raise",
    biomechanicalPattern: "rear_delt_isolation",
    equipmentTypes: ["dumbbell", "machine"],
    equipmentAccess: ["full_gym", "dumbbells_only", "machines_only", "minimal_home_gym"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: [
      "pull",
      "upper",
      "full_body",
      "female_friendly",
      "beginner_friendly",
      "bodybuilding",
    ],
    styleTags: ["bodybuilding", "pump", "high_volume"],
    laterality: "bilateral",
    fatigueCost: 1,
    complexity: 1,
    jointStress: "low",
    jointStressAreas: ["shoulders"],
    progressionType: "load_reps",
    emphasis: ["rear_delt_bias"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["back", "pull", "upper", "back_rear_delts", "shoulders_arms"],
    liftRole: "isolation",
    unilateralBias: "optional",
    equipmentFit: {
      full_gym: "good",
      dumbbells_only: "good",
      machines_only: "best",
      minimal_home_gym: "good",
    },
    difficultyTier: "beginner",
  },
{
  id: "pull_up",
  name: "Pull-Up",
  primaryMuscle: "lats",
  secondaryMuscles: ["back", "biceps", "core"],
  category: "main",
  movementPattern: "vertical_pull",
  biomechanicalPattern: "compound_pull",
  equipmentTypes: ["bodyweight"],
  equipmentAccess: ["full_gym", "bodyweight_only", "minimal_home_gym"],
  levels: ["intermediate", "advanced"],
  workoutTags: ["pull", "upper", "full_body", "bodybuilding"],
  styleTags: ["strength_size", "old_school_mass", "balanced"],
  laterality: "bilateral",
  fatigueCost: 4,
  complexity: 3,
  jointStress: "moderate",
  jointStressAreas: ["shoulders", "elbows"],
  progressionType: "bodyweight_reps",
  emphasis: ["lat_width"],
  isPrimaryCompound: true,
  isStable: true,
  sessionFocuses: ["back", "pull", "upper", "back_biceps", "back_rear_delts"],
  liftRole: "anchor",
  unilateralBias: "none",
  equipmentFit: {
    full_gym: "best",
    bodyweight_only: "best",
    minimal_home_gym: "good",
  },
  difficultyTier: "intermediate",
},
{
  id: "chin_up",
  name: "Chin-Up",
  primaryMuscle: "lats",
  secondaryMuscles: ["biceps", "back", "core"],
  category: "main",
  movementPattern: "vertical_pull",
  biomechanicalPattern: "compound_pull",
  equipmentTypes: ["bodyweight"],
  equipmentAccess: ["full_gym", "bodyweight_only", "minimal_home_gym"],
  levels: ["intermediate", "advanced"],
  workoutTags: ["pull", "upper", "full_body", "bodybuilding"],
  styleTags: ["balanced", "old_school_mass", "strength_size"],
  laterality: "bilateral",
  fatigueCost: 4,
  complexity: 3,
  jointStress: "moderate",
  jointStressAreas: ["elbows", "shoulders"],
  progressionType: "bodyweight_reps",
  emphasis: ["lat_width", "bicep_peak"],
  isPrimaryCompound: true,
  isStable: true,
  sessionFocuses: ["back", "pull", "upper", "back_biceps"],
  liftRole: "anchor",
  unilateralBias: "none",
  equipmentFit: {
    full_gym: "best",
    bodyweight_only: "best",
    minimal_home_gym: "good",
  },
  difficultyTier: "intermediate",
},
{
  id: "assisted_pull_up",
  name: "Assisted Pull-Up",
  primaryMuscle: "lats",
  secondaryMuscles: ["back", "biceps"],
  category: "main",
  movementPattern: "vertical_pull",
  biomechanicalPattern: "compound_pull",
  equipmentTypes: ["machine"],
  equipmentAccess: ["full_gym", "machines_only"],
  levels: ["beginner", "intermediate", "advanced"],
  workoutTags: ["pull", "upper", "beginner_friendly", "bodybuilding"],
  styleTags: ["balanced", "bodybuilding", "high_volume"],
  laterality: "bilateral",
  fatigueCost: 2,
  complexity: 1,
  jointStress: "low",
  jointStressAreas: ["shoulders", "elbows"],
  progressionType: "load_reps",
  emphasis: ["lat_width"],
  isPrimaryCompound: true,
  isStable: true,
  sessionFocuses: ["back", "pull", "upper", "back_biceps"],
  liftRole: "anchor",
  unilateralBias: "none",
  equipmentFit: {
    full_gym: "best",
    machines_only: "best",
  },
  difficultyTier: "beginner",
},
{
  id: "t_bar_row",
  name: "T-Bar Row",
  primaryMuscle: "back",
  secondaryMuscles: ["lats", "upper_back", "biceps"],
  category: "main",
  movementPattern: "horizontal_pull",
  biomechanicalPattern: "compound_pull",
  equipmentTypes: ["plate_loaded", "barbell"],
  equipmentAccess: ["full_gym", "barbell_rack"],
  levels: ["intermediate", "advanced"],
  workoutTags: ["pull", "upper", "bodybuilding"],
  styleTags: ["old_school_mass", "strength_size", "bodybuilding"],
  laterality: "bilateral",
  fatigueCost: 4,
  complexity: 3,
  jointStress: "moderate",
  jointStressAreas: ["lower_back"],
  progressionType: "load_reps",
  emphasis: ["mid_back_thickness"],
  isPrimaryCompound: true,
  isStable: false,
  sessionFocuses: ["back", "pull", "upper", "back_biceps", "back_rear_delts"],
  liftRole: "anchor",
  unilateralBias: "none",
  equipmentFit: {
    full_gym: "best",
    barbell_rack: "good",
  },
  difficultyTier: "advanced",
},
{
  id: "deadlift",
  name: "Deadlift",
  primaryMuscle: "hamstrings",
  secondaryMuscles: ["glutes", "back", "lower_back", "core"],
  category: "main",
  movementPattern: "hinge",
  biomechanicalPattern: "hip_hinge",
  equipmentTypes: ["barbell"],
  equipmentAccess: ["full_gym", "barbell_rack"],
  levels: ["intermediate", "advanced"],
  workoutTags: ["lower", "full_body", "pull"],
  styleTags: ["strength_size", "old_school_mass"],
  laterality: "bilateral",
  fatigueCost: 5,
  complexity: 4,
  jointStress: "high",
  jointStressAreas: ["lower_back", "hips"],
  progressionType: "load_reps",
  emphasis: ["hamstring_bias", "glute_bias"],
  isPrimaryCompound: true,
  isStable: false,
  sessionFocuses: ["legs", "lower", "full_body", "glutes_hamstrings"],
  liftRole: "anchor",
  unilateralBias: "none",
  equipmentFit: {
    full_gym: "best",
    barbell_rack: "best",
  },
  difficultyTier: "advanced",
},
{
  id: "trap_bar_deadlift",
  name: "Trap Bar Deadlift",
  primaryMuscle: "quads",
  secondaryMuscles: ["glutes", "hamstrings", "back", "core"],
  category: "main",
  movementPattern: "hinge",
  biomechanicalPattern: "hip_hinge",
  equipmentTypes: ["barbell"],
  equipmentAccess: ["full_gym", "barbell_rack"],
  levels: ["beginner", "intermediate", "advanced"],
  workoutTags: ["lower", "full_body", "pull", "beginner_friendly"],
  styleTags: ["strength_size", "balanced"],
  laterality: "bilateral",
  fatigueCost: 4,
  complexity: 2,
  jointStress: "moderate",
  jointStressAreas: ["lower_back", "hips", "knees"],
  progressionType: "load_reps",
  emphasis: ["quad_bias", "glute_bias"],
  isPrimaryCompound: true,
  isStable: true,
  sessionFocuses: ["legs", "lower", "full_body", "quads_glutes"],
  liftRole: "anchor",
  unilateralBias: "none",
  equipmentFit: {
    full_gym: "best",
    barbell_rack: "good",
  },
  difficultyTier: "beginner",
},
{
  id: "front_squat",
  name: "Front Squat",
  primaryMuscle: "quads",
  secondaryMuscles: ["glutes", "core", "upper_back"],
  category: "main",
  movementPattern: "squat",
  biomechanicalPattern: "squat_pattern",
  equipmentTypes: ["barbell"],
  equipmentAccess: ["full_gym", "barbell_rack"],
  levels: ["intermediate", "advanced"],
  workoutTags: ["lower", "full_body"],
  styleTags: ["strength_size", "balanced"],
  laterality: "bilateral",
  fatigueCost: 4,
  complexity: 4,
  jointStress: "moderate",
  jointStressAreas: ["knees", "wrists", "upper_back"],
  progressionType: "load_reps",
  emphasis: ["quad_bias"],
  isPrimaryCompound: true,
  isStable: false,
  sessionFocuses: ["legs", "lower", "quads_glutes", "full_body"],
  liftRole: "anchor",
  unilateralBias: "none",
  equipmentFit: {
    full_gym: "best",
    barbell_rack: "best",
  },
  difficultyTier: "advanced",
},
{
  id: "pendulum_squat",
  name: "Pendulum Squat",
  primaryMuscle: "quads",
  secondaryMuscles: ["glutes"],
  category: "main",
  movementPattern: "squat",
  biomechanicalPattern: "squat_pattern",
  equipmentTypes: ["machine"],
  equipmentAccess: ["full_gym", "machines_only"],
  levels: ["intermediate", "advanced"],
  workoutTags: ["lower", "bodybuilding"],
  styleTags: ["bodybuilding", "high_volume", "pump", "intensity"],
  laterality: "bilateral",
  fatigueCost: 3,
  complexity: 1,
  jointStress: "moderate",
  jointStressAreas: ["knees", "hips"],
  progressionType: "load_reps",
  emphasis: ["quad_bias"],
  isPrimaryCompound: true,
  isStable: true,
  sessionFocuses: ["legs", "lower", "quads_glutes", "quads_calves"],
  liftRole: "anchor",
  unilateralBias: "none",
  equipmentFit: {
    full_gym: "best",
    machines_only: "best",
  },
  difficultyTier: "intermediate",
},
{
  id: "front_foot_elevated_split_squat",
  name: "Front Foot Elevated Split Squat",
  primaryMuscle: "quads",
  secondaryMuscles: ["glutes", "hamstrings"],
  category: "accessory",
  movementPattern: "lunge",
  biomechanicalPattern: "single_leg",
  equipmentTypes: ["dumbbell", "bodyweight", "smith"],
  equipmentAccess: ["full_gym", "dumbbells_only", "minimal_home_gym", "bodyweight_only"],
  levels: ["intermediate", "advanced"],
  workoutTags: ["lower", "bodybuilding", "glute_friendly", "female_friendly"],
  styleTags: ["bodybuilding", "high_volume", "pump"],
  laterality: "unilateral",
  fatigueCost: 3,
  complexity: 2,
  jointStress: "moderate",
  jointStressAreas: ["knees", "hips"],
  progressionType: "load_reps",
  emphasis: ["quad_bias", "glute_bias"],
  isPrimaryCompound: false,
  isStable: false,
  sessionFocuses: ["legs", "lower", "quads_glutes", "unilateral_lower"],
  liftRole: "primary",
  unilateralBias: "preferred",
  equipmentFit: {
    full_gym: "best",
    dumbbells_only: "best",
    minimal_home_gym: "good",
    bodyweight_only: "backup",
  },
  difficultyTier: "intermediate",
},
{
  id: "back_extension_45",
  name: "45 Degree Back Extension",
  primaryMuscle: "lower_back",
  secondaryMuscles: ["glutes", "hamstrings"],
  category: "accessory",
  movementPattern: "hinge",
  biomechanicalPattern: "hip_hinge",
  equipmentTypes: ["bodyweight", "plate_loaded", "dumbbell"],
  equipmentAccess: ["full_gym", "minimal_home_gym"],
  levels: ["beginner", "intermediate", "advanced"],
  workoutTags: ["lower", "full_body", "glute_friendly"],
  styleTags: ["balanced", "bodybuilding", "high_volume"],
  laterality: "bilateral",
  fatigueCost: 2,
  complexity: 1,
  jointStress: "low",
  jointStressAreas: ["lower_back", "hips"],
  progressionType: "load_reps",
  emphasis: ["glute_bias", "hamstring_bias"],
  isPrimaryCompound: false,
  isStable: true,
  sessionFocuses: ["legs", "lower", "glutes_hamstrings", "full_body"],
  liftRole: "secondary",
  unilateralBias: "none",
  equipmentFit: {
    full_gym: "best",
    minimal_home_gym: "backup",
  },
  difficultyTier: "beginner",
},
{
  id: "arnold_press",
  name: "Arnold Press",
  primaryMuscle: "shoulders",
  secondaryMuscles: ["front_delts", "side_delts", "triceps"],
  category: "accessory",
  movementPattern: "vertical_press",
  biomechanicalPattern: "compound_press",
  equipmentTypes: ["dumbbell"],
  equipmentAccess: ["full_gym", "dumbbells_only", "minimal_home_gym"],
  levels: ["intermediate", "advanced"],
  workoutTags: ["push", "upper", "bodybuilding"],
  styleTags: ["bodybuilding", "pump", "old_school_mass"],
  laterality: "bilateral",
  fatigueCost: 3,
  complexity: 2,
  jointStress: "moderate",
  jointStressAreas: ["shoulders"],
  progressionType: "load_reps",
  emphasis: ["front_delt_bias", "side_delt_bias"],
  isPrimaryCompound: false,
  isStable: true,
  sessionFocuses: ["shoulders", "push", "upper", "shoulders_arms", "chest_shoulders"],
  liftRole: "primary",
  unilateralBias: "none",
  equipmentFit: {
    full_gym: "good",
    dumbbells_only: "best",
    minimal_home_gym: "best",
  },
  difficultyTier: "intermediate",
},
{
  id: "reverse_pec_deck",
  name: "Reverse Pec Deck",
  primaryMuscle: "rear_delts",
  secondaryMuscles: ["upper_back"],
  category: "isolation",
  movementPattern: "raise",
  biomechanicalPattern: "rear_delt_isolation",
  equipmentTypes: ["machine"],
  equipmentAccess: ["full_gym", "machines_only"],
  levels: ["beginner", "intermediate", "advanced"],
  workoutTags: ["pull", "upper", "bodybuilding", "beginner_friendly"],
  styleTags: ["bodybuilding", "pump", "high_volume"],
  laterality: "bilateral",
  fatigueCost: 1,
  complexity: 1,
  jointStress: "low",
  jointStressAreas: ["shoulders"],
  progressionType: "load_reps",
  emphasis: ["rear_delt_bias"],
  isPrimaryCompound: false,
  isStable: true,
  sessionFocuses: ["back", "pull", "upper", "back_rear_delts", "shoulders_arms"],
  liftRole: "isolation",
  unilateralBias: "none",
  equipmentFit: {
    full_gym: "best",
    machines_only: "best",
  },
  difficultyTier: "beginner",
},
{
  id: "preacher_curl",
  name: "Preacher Curl",
  primaryMuscle: "biceps",
  secondaryMuscles: ["forearms"],
  category: "isolation",
  movementPattern: "curl",
  biomechanicalPattern: "elbow_flexion",
  equipmentTypes: ["barbell", "dumbbell", "machine"],
  equipmentAccess: ["full_gym", "barbell_rack", "dumbbells_only", "machines_only"],
  levels: ["beginner", "intermediate", "advanced"],
  workoutTags: ["pull", "upper", "bodybuilding", "beginner_friendly"],
  styleTags: ["bodybuilding", "pump", "high_volume", "old_school_mass"],
  laterality: "bilateral",
  fatigueCost: 1,
  complexity: 1,
  jointStress: "moderate",
  jointStressAreas: ["elbows"],
  progressionType: "load_reps",
  emphasis: ["bicep_peak"],
  isPrimaryCompound: false,
  isStable: true,
  sessionFocuses: ["arms", "pull", "upper", "back_biceps", "shoulders_arms"],
  liftRole: "isolation",
  unilateralBias: "none",
  equipmentFit: {
    full_gym: "best",
    barbell_rack: "good",
    dumbbells_only: "good",
    machines_only: "best",
  },
  difficultyTier: "beginner",
},
{
  id: "cable_curl",
  name: "Cable Curl",
  primaryMuscle: "biceps",
  secondaryMuscles: ["forearms"],
  category: "isolation",
  movementPattern: "curl",
  biomechanicalPattern: "elbow_flexion",
  equipmentTypes: ["cable"],
  equipmentAccess: ["full_gym"],
  levels: ["beginner", "intermediate", "advanced"],
  workoutTags: ["pull", "upper", "bodybuilding", "beginner_friendly"],
  styleTags: ["bodybuilding", "pump", "high_volume"],
  laterality: "bilateral",
  fatigueCost: 1,
  complexity: 1,
  jointStress: "low",
  jointStressAreas: ["elbows"],
  progressionType: "load_reps",
  emphasis: ["bicep_peak"],
  isPrimaryCompound: false,
  isStable: true,
  sessionFocuses: ["arms", "pull", "upper", "back_biceps", "shoulders_arms"],
  liftRole: "isolation",
  unilateralBias: "none",
  equipmentFit: {
    full_gym: "best",
  },
  difficultyTier: "beginner",
},
{
  id: "ez_bar_curl",
  name: "EZ-Bar Curl",
  primaryMuscle: "biceps",
  secondaryMuscles: ["forearms"],
  category: "accessory",
  movementPattern: "curl",
  biomechanicalPattern: "elbow_flexion",
  equipmentTypes: ["barbell"],
  equipmentAccess: ["full_gym", "barbell_rack"],
  levels: ["beginner", "intermediate", "advanced"],
  workoutTags: ["pull", "upper", "bodybuilding"],
  styleTags: ["old_school_mass", "bodybuilding", "balanced"],
  laterality: "bilateral",
  fatigueCost: 1,
  complexity: 1,
  jointStress: "low",
  jointStressAreas: ["elbows", "wrists"],
  progressionType: "load_reps",
  emphasis: ["bicep_peak"],
  isPrimaryCompound: false,
  isStable: true,
  sessionFocuses: ["arms", "pull", "upper", "back_biceps", "shoulders_arms"],
  liftRole: "accessory",
  unilateralBias: "none",
  equipmentFit: {
    full_gym: "good",
    barbell_rack: "best",
  },
  difficultyTier: "beginner",
},
{
  id: "close_grip_bench_press",
  name: "Close-Grip Bench Press",
  primaryMuscle: "triceps",
  secondaryMuscles: ["chest", "front_delts"],
  category: "main",
  movementPattern: "horizontal_press",
  biomechanicalPattern: "compound_press",
  equipmentTypes: ["barbell"],
  equipmentAccess: ["full_gym", "barbell_rack"],
  levels: ["intermediate", "advanced"],
  workoutTags: ["push", "upper", "bodybuilding"],
  styleTags: ["strength_size", "old_school_mass"],
  laterality: "bilateral",
  fatigueCost: 4,
  complexity: 3,
  jointStress: "moderate",
  jointStressAreas: ["wrists", "elbows", "shoulders"],
  progressionType: "load_reps",
  emphasis: ["tricep_long_head"],
  isPrimaryCompound: true,
  isStable: false,
  sessionFocuses: ["arms", "push", "upper", "chest_triceps", "shoulders_arms"],
  liftRole: "anchor",
  unilateralBias: "none",
  equipmentFit: {
    full_gym: "best",
    barbell_rack: "best",
  },
  difficultyTier: "advanced",
},
{
  id: "dips",
  name: "Dips",
  primaryMuscle: "triceps",
  secondaryMuscles: ["chest", "front_delts"],
  category: "main",
  movementPattern: "bodyweight_push",
  biomechanicalPattern: "compound_press",
  equipmentTypes: ["bodyweight"],
  equipmentAccess: ["full_gym", "bodyweight_only", "minimal_home_gym"],
  levels: ["intermediate", "advanced"],
  workoutTags: ["push", "upper", "bodybuilding"],
  styleTags: ["old_school_mass", "strength_size", "bodybuilding"],
  laterality: "bilateral",
  fatigueCost: 3,
  complexity: 3,
  jointStress: "moderate",
  jointStressAreas: ["shoulders", "elbows"],
  progressionType: "bodyweight_reps",
  emphasis: ["tricep_long_head", "mid_chest"],
  isPrimaryCompound: true,
  isStable: true,
  sessionFocuses: ["arms", "push", "upper", "chest_triceps", "chest_shoulders"],
  liftRole: "anchor",
  unilateralBias: "none",
  equipmentFit: {
    full_gym: "best",
    bodyweight_only: "good",
    minimal_home_gym: "backup",
  },
  difficultyTier: "intermediate",
},
{
  id: "machine_dip",
  name: "Machine Dip",
  primaryMuscle: "triceps",
  secondaryMuscles: ["chest", "front_delts"],
  category: "accessory",
  movementPattern: "tricep_extension",
  biomechanicalPattern: "compound_press",
  equipmentTypes: ["machine"],
  equipmentAccess: ["full_gym", "machines_only"],
  levels: ["beginner", "intermediate", "advanced"],
  workoutTags: ["push", "upper", "bodybuilding", "beginner_friendly"],
  styleTags: ["bodybuilding", "pump", "high_volume"],
  laterality: "bilateral",
  fatigueCost: 2,
  complexity: 1,
  jointStress: "low",
  jointStressAreas: ["elbows", "shoulders"],
  progressionType: "load_reps",
  emphasis: ["tricep_long_head"],
  isPrimaryCompound: false,
  isStable: true,
  sessionFocuses: ["arms", "push", "upper", "chest_triceps", "shoulders_arms"],
  liftRole: "primary",
  unilateralBias: "none",
  equipmentFit: {
    full_gym: "best",
    machines_only: "best",
  },
  difficultyTier: "beginner",
},
{
  id: "hanging_leg_raise",
  name: "Hanging Leg Raise",
  primaryMuscle: "core",
  secondaryMuscles: ["hip_flexors", "forearms"],
  category: "accessory",
  movementPattern: "core",
  biomechanicalPattern: "core_flexion",
  equipmentTypes: ["bodyweight"],
  equipmentAccess: ["full_gym", "bodyweight_only", "minimal_home_gym"],
  levels: ["intermediate", "advanced"],
  workoutTags: ["full_body", "upper", "lower"],
  styleTags: ["balanced", "high_volume"],
  laterality: "bilateral",
  fatigueCost: 2,
  complexity: 2,
  jointStress: "low",
  jointStressAreas: ["hips", "shoulders"],
  progressionType: "bodyweight_reps",
  emphasis: ["core_stability"],
  isPrimaryCompound: false,
  isStable: false,
  sessionFocuses: ["full_body", "upper", "lower"],
  liftRole: "accessory",
  unilateralBias: "none",
  equipmentFit: {
    full_gym: "best",
    bodyweight_only: "good",
    minimal_home_gym: "good",
  },
  difficultyTier: "intermediate",
},
{
  id: "cable_crunch",
  name: "Cable Crunch",
  primaryMuscle: "core",
  secondaryMuscles: [],
  category: "isolation",
  movementPattern: "core",
  biomechanicalPattern: "core_flexion",
  equipmentTypes: ["cable"],
  equipmentAccess: ["full_gym"],
  levels: ["beginner", "intermediate", "advanced"],
  workoutTags: ["full_body", "beginner_friendly"],
  styleTags: ["bodybuilding", "pump", "high_volume"],
  laterality: "bilateral",
  fatigueCost: 1,
  complexity: 1,
  jointStress: "low",
  jointStressAreas: [],
  progressionType: "load_reps",
  emphasis: ["core_stability"],
  isPrimaryCompound: false,
  isStable: true,
  sessionFocuses: ["full_body", "upper", "lower"],
  liftRole: "isolation",
  unilateralBias: "none",
  equipmentFit: {
    full_gym: "best",
  },
  difficultyTier: "beginner",
},
  {
    id: "barbell_curl",
    name: "Barbell Curl",
    primaryMuscle: "biceps",
    secondaryMuscles: ["forearms"],
    category: "accessory",
    movementPattern: "curl",
    biomechanicalPattern: "elbow_flexion",
    equipmentTypes: ["barbell"],
    equipmentAccess: ["full_gym", "barbell_rack"],
    levels: ["intermediate", "advanced"],
    workoutTags: ["pull", "upper", "bodybuilding"],
    styleTags: ["old_school_mass", "balanced"],
    laterality: "bilateral",
    fatigueCost: 1,
    complexity: 2,
    jointStress: "moderate",
    jointStressAreas: ["elbows"],
    progressionType: "load_reps",
    emphasis: ["bicep_peak"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["arms", "pull", "upper", "back_biceps", "shoulders_arms"],
    liftRole: "accessory",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "good",
      barbell_rack: "best",
    },
    difficultyTier: "intermediate",
  },
  {
    id: "hammer_curls",
    name: "Hammer Curls",
    primaryMuscle: "biceps",
    secondaryMuscles: ["forearms"],
    category: "accessory",
    movementPattern: "curl",
    biomechanicalPattern: "elbow_flexion",
    equipmentTypes: ["dumbbell"],
    equipmentAccess: ["full_gym", "dumbbells_only", "minimal_home_gym"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: ["pull", "upper", "beginner_friendly", "bodybuilding"],
    styleTags: ["balanced", "bodybuilding", "old_school_mass"],
    laterality: "bilateral",
    fatigueCost: 1,
    complexity: 1,
    jointStress: "low",
    jointStressAreas: ["elbows"],
    progressionType: "load_reps",
    emphasis: ["bicep_peak"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["arms", "pull", "upper", "back_biceps", "shoulders_arms"],
    liftRole: "accessory",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "good",
      dumbbells_only: "best",
      minimal_home_gym: "best",
    },
    difficultyTier: "beginner",
  },
  {
    id: "incline_dumbbell_curl",
    name: "Incline Dumbbell Curl",
    primaryMuscle: "biceps",
    secondaryMuscles: ["forearms"],
    category: "isolation",
    movementPattern: "curl",
    biomechanicalPattern: "elbow_flexion",
    equipmentTypes: ["dumbbell"],
    equipmentAccess: ["full_gym", "dumbbells_only", "minimal_home_gym"],
    levels: ["intermediate", "advanced"],
    workoutTags: ["pull", "upper", "bodybuilding"],
    styleTags: ["bodybuilding", "pump", "high_volume"],
    laterality: "bilateral",
    fatigueCost: 1,
    complexity: 1,
    jointStress: "low",
    jointStressAreas: ["elbows"],
    progressionType: "load_reps",
    emphasis: ["bicep_peak"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["arms", "pull", "upper", "back_biceps", "shoulders_arms"],
    liftRole: "isolation",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "good",
      dumbbells_only: "best",
      minimal_home_gym: "best",
    },
    difficultyTier: "intermediate",
  },
  {
    id: "tricep_pressdown",
    name: "Tricep Pressdown",
    primaryMuscle: "triceps",
    secondaryMuscles: [],
    category: "isolation",
    movementPattern: "tricep_extension",
    biomechanicalPattern: "elbow_extension",
    equipmentTypes: ["cable"],
    equipmentAccess: ["full_gym"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: [
      "push",
      "upper",
      "beginner_friendly",
      "female_friendly",
      "bodybuilding",
    ],
    styleTags: ["balanced", "bodybuilding", "pump", "high_volume"],
    laterality: "bilateral",
    fatigueCost: 1,
    complexity: 1,
    jointStress: "low",
    jointStressAreas: ["elbows"],
    progressionType: "load_reps",
    emphasis: ["tricep_long_head"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["arms", "push", "upper", "chest_triceps", "shoulders_arms"],
    liftRole: "isolation",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "best",
    },
    difficultyTier: "beginner",
  },
  {
    id: "overhead_cable_tricep_extension",
    name: "Overhead Cable Tricep Extension",
    primaryMuscle: "triceps",
    secondaryMuscles: [],
    category: "isolation",
    movementPattern: "tricep_extension",
    biomechanicalPattern: "elbow_extension",
    equipmentTypes: ["cable"],
    equipmentAccess: ["full_gym"],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: ["push", "upper", "bodybuilding"],
    styleTags: ["bodybuilding", "pump", "high_volume"],
    laterality: "bilateral",
    fatigueCost: 1,
    complexity: 1,
    jointStress: "low",
    jointStressAreas: ["elbows"],
    progressionType: "load_reps",
    emphasis: ["tricep_long_head"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["arms", "push", "upper", "chest_triceps", "shoulders_arms"],
    liftRole: "isolation",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "best",
    },
    difficultyTier: "beginner",
  },
  {
    id: "skull_crushers",
    name: "Skull Crushers",
    primaryMuscle: "triceps",
    secondaryMuscles: [],
    category: "accessory",
    movementPattern: "tricep_extension",
    biomechanicalPattern: "elbow_extension",
    equipmentTypes: ["barbell", "dumbbell"],
    equipmentAccess: ["full_gym", "barbell_rack", "dumbbells_only"],
    levels: ["intermediate", "advanced"],
    workoutTags: ["push", "upper", "bodybuilding"],
    styleTags: ["old_school_mass", "bodybuilding"],
    laterality: "bilateral",
    fatigueCost: 2,
    complexity: 2,
    jointStress: "high",
    jointStressAreas: ["elbows"],
    progressionType: "load_reps",
    emphasis: ["tricep_long_head"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["arms", "push", "upper", "chest_triceps", "shoulders_arms"],
    liftRole: "accessory",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "good",
      barbell_rack: "good",
      dumbbells_only: "good",
    },
    difficultyTier: "intermediate",
  },

  {
    id: "plank",
    name: "Plank",
    primaryMuscle: "core",
    secondaryMuscles: ["shoulders"],
    category: "accessory",
    movementPattern: "core",
    biomechanicalPattern: "core_stability",
    equipmentTypes: ["bodyweight"],
    equipmentAccess: [
      "full_gym",
      "bodyweight_only",
      "minimal_home_gym",
      "dumbbells_only",
      "barbell_rack",
      "machines_only",
    ],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: ["full_body", "beginner_friendly"],
    styleTags: ["balanced"],
    laterality: "bilateral",
    fatigueCost: 1,
    complexity: 1,
    jointStress: "low",
    jointStressAreas: [],
    progressionType: "time_hold",
    emphasis: ["core_stability"],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["full_body", "upper", "lower"],
    liftRole: "accessory",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "backup",
      bodyweight_only: "best",
      minimal_home_gym: "best",
      dumbbells_only: "good",
      barbell_rack: "good",
      machines_only: "backup",
    },
    difficultyTier: "beginner",
  },
  {
    id: "crunch",
    name: "Crunch",
    primaryMuscle: "core",
    secondaryMuscles: [],
    category: "isolation",
    movementPattern: "core",
    biomechanicalPattern: "core_flexion",
    equipmentTypes: ["bodyweight"],
    equipmentAccess: [
      "full_gym",
      "bodyweight_only",
      "minimal_home_gym",
      "dumbbells_only",
      "barbell_rack",
      "machines_only",
    ],
    levels: ["beginner", "intermediate", "advanced"],
    workoutTags: ["full_body", "beginner_friendly"],
    styleTags: ["balanced", "pump"],
    laterality: "bilateral",
    fatigueCost: 1,
    complexity: 1,
    jointStress: "low",
    jointStressAreas: [],
    progressionType: "reps_only",
    emphasis: [],
    isPrimaryCompound: false,
    isStable: true,
    sessionFocuses: ["full_body", "upper", "lower"],
    liftRole: "isolation",
    unilateralBias: "none",
    equipmentFit: {
      full_gym: "backup",
      bodyweight_only: "best",
      minimal_home_gym: "best",
      dumbbells_only: "good",
      barbell_rack: "good",
      machines_only: "backup",
    },
    difficultyTier: "beginner",
  },
];